dummy_invoices = [
    {
        "Invoices": [
            {
                "AmountCredited": 0.0,
                "AmountDue": 825.0,
                "AmountPaid": 0.0,
                "Contact": {
                    "Addresses": [],
                    "ContactGroups": [],
                    "ContactID": "860b99a9-0958-4c8d-a98f-bb1f092b16bb",
                    "ContactPersons": [],
                    "HasAttachments": False,
                    "HasValidationErrors": False,
                    "Name": "DIISR - Small Business Services",
                    "Phones": [],
                },
                "CreditNotes": [],
                "CurrencyCode": "AUD",
                "Date": "/Date(1723766400000)/",
                "DueDate": "/Date(1725494400000)/",
                "HasAttachments": False,
                "HasErrors": False,
                "InvoiceID": "0e64a623-c2a1-446a-93ed-eb897f118cbc",
                "InvoiceNumber": "ORC1027",
                "IsDiscounted": False,
                "LineAmountTypes": "Exclusive",
                "LineItems": [
                    {
                        "AccountCode": "200",
                        "Description": "Feedback sessions with your stakeholders",
                        "LineAmount": 750.0,
                        "LineItemID": "ad4dfaa6-9705-4c58-8c39-3ee3fc3c6bbf",
                        "Quantity": 5.0,
                        "TaxAmount": 75.0,
                        "TaxType": "OUTPUT",
                        "Tracking": [
                            {
                                "Name": "Region",
                                "Option": "Eastside",
                                "TrackingCategoryID": "093af706-c2aa-4d97-a4ce-2d205a017eac",
                            }
                        ],
                        "UnitAmount": 150.0,
                    }
                ],
                "Overpayments": [],
                "Payments": [],
                "Prepayments": [],
                "Reference": "Portal proj",
                "Status": "SUBMITTED",
                "SubTotal": 750.0,
                "Total": 825.0,
                "TotalTax": 75.0,
                "Type": "ACCREC",
                "UpdatedDateUTC": "/Date(1222863497207+0000)/",
                "OnlineInvoiceUrl": "https://go.xero.com/",
            },
            {
                "AmountCredited": 0.0,
                "AmountDue": 550.0,
                "AmountPaid": 0.0,
                "Contact": {
                    "Addresses": [],
                    "ContactGroups": [],
                    "ContactID": "1b2be6e9-8d58-4da9-aaf8-4fe5471b653c",
                    "ContactPersons": [],
                    "HasAttachments": False,
                    "HasValidationErrors": False,
                    "Name": "Hamilton Smith Pty",
                    "Phones": [],
                },
                "CreditNotes": [],
                "CurrencyCode": "AUD",
                "Date": "/Date(1723766400000)/",
                "DueDate": "/Date(1725062400000)/",
                "HasAttachments": False,
                "HasErrors": False,
                "InvoiceID": "9868b472-1983-48e9-8edf-7e81ddf2c03a",
                "InvoiceNumber": "ORC1028",
                "IsDiscounted": False,
                "LineAmountTypes": "Exclusive",
                "LineItems": [
                    {
                        "AccountCode": "200",
                        "Description": "Desktop/network support via email & phone.\r\nPer month fixed fee for minimum 20 hours/month.",
                        "ItemCode": "Support-M",
                        "LineAmount": 500.0,
                        "LineItemID": "f543614d-7a9a-41ec-8c10-eaecbf78383d",
                        "Quantity": 1.0,
                        "TaxAmount": 50.0,
                        "TaxType": "OUTPUT",
                        "Tracking": [],
                        "UnitAmount": 500.0,
                    }
                ],
                "Overpayments": [],
                "Payments": [],
                "Prepayments": [],
                "Reference": "Monthly support",
                "Status": "DRAFT",
                "SubTotal": 500.0,
                "Total": 550.0,
                "TotalTax": 50.0,
                "Type": "ACCREC",
                "UpdatedDateUTC": "/Date(1222863623553+0000)/",
                "OnlineInvoiceUrl": "https://go.xero.com/",
            },
            {
                "AmountCredited": 0.0,
                "AmountDue": 550.0,
                "AmountPaid": 0.0,
                "Contact": {
                    "Addresses": [],
                    "ContactGroups": [],
                    "ContactID": "755f1475-d255-43a8-bedc-5ea7fd26c71f",
                    "ContactPersons": [],
                    "HasAttachments": False,
                    "HasValidationErrors": False,
                    "Name": "Yarra Transport",
                    "Phones": [],
                },
                "CreditNotes": [],
                "CurrencyCode": "AUD",
                "Date": "/Date(1723766400000)/",
                "DueDate": "/Date(1725062400000)/",
                "HasAttachments": False,
                "HasErrors": False,
                "InvoiceID": "ab63738a-370a-43a5-bfa3-620d684e66d0",
                "InvoiceNumber": "ORC1029",
                "IsDiscounted": False,
                "LineAmountTypes": "Exclusive",
                "LineItems": [
                    {
                        "AccountCode": "200",
                        "Description": "Desktop/network support via email & phone.\r\nPer month fixed fee for minimum 20 hours/month.",
                        "ItemCode": "Support-M",
                        "LineAmount": 500.0,
                        "LineItemID": "0175aa7b-d7e1-47c8-909e-90f032d7edc5",
                        "Quantity": 1.0,
                        "TaxAmount": 50.0,
                        "TaxType": "OUTPUT",
                        "Tracking": [],
                        "UnitAmount": 500.0,
                    }
                ],
                "Overpayments": [],
                "Payments": [],
                "Prepayments": [],
                "Reference": "Monthly support",
                "Status": "DRAFT",
                "SubTotal": 500.0,
                "Total": 550.0,
                "TotalTax": 50.0,
                "Type": "ACCREC",
                "UpdatedDateUTC": "/Date(1222863623663+0000)/",
                "OnlineInvoiceUrl": "https://go.xero.com/",
            },
            {
                "AmountCredited": 0.0,
                "AmountDue": 550.0,
                "AmountPaid": 0.0,
                "Contact": {
                    "Addresses": [],
                    "ContactGroups": [],
                    "ContactID": "13cd4c47-baa6-4f07-93f6-6442310df4bf",
                    "ContactPersons": [],
                    "HasAttachments": False,
                    "HasValidationErrors": False,
                    "Name": "Port Phillip Freight",
                    "Phones": [],
                },
                "CreditNotes": [],
                "CurrencyCode": "AUD",
                "Date": "/Date(1723766400000)/",
                "DueDate": "/Date(1725062400000)/",
                "HasAttachments": False,
                "HasErrors": False,
                "InvoiceID": "66fbe37f-49b1-43fd-97ed-85114022cd2f",
                "InvoiceNumber": "ORC1030",
                "IsDiscounted": False,
                "LineAmountTypes": "Exclusive",
                "LineItems": [
                    {
                        "AccountCode": "200",
                        "Description": "Desktop/network support via email & phone.\r\nPer month fixed fee for minimum 20 hours/month.",
                        "ItemCode": "Support-M",
                        "LineAmount": 500.0,
                        "LineItemID": "5400a5f8-c26b-4461-a714-0fa7714c359b",
                        "Quantity": 1.0,
                        "TaxAmount": 50.0,
                        "TaxType": "OUTPUT",
                        "Tracking": [],
                        "UnitAmount": 500.0,
                    }
                ],
                "Overpayments": [],
                "Payments": [],
                "Prepayments": [],
                "Reference": "Monthly support",
                "Status": "DRAFT",
                "SubTotal": 500.0,
                "Total": 550.0,
                "TotalTax": 50.0,
                "Type": "ACCREC",
                "UpdatedDateUTC": "/Date(1222863623727+0000)/",
                "OnlineInvoiceUrl": "https://go.xero.com/",
            },
            {
                "AmountCredited": 0.0,
                "AmountDue": 550.0,
                "AmountPaid": 0.0,
                "Contact": {
                    "Addresses": [],
                    "ContactGroups": [],
                    "ContactID": "6de0b0cf-560c-4503-aab3-e1543c329deb",
                    "ContactPersons": [],
                    "HasAttachments": False,
                    "HasValidationErrors": False,
                    "Name": "Rex Media Group",
                    "Phones": [],
                },
                "CreditNotes": [],
                "CurrencyCode": "AUD",
                "Date": "/Date(1723766400000)/",
                "DueDate": "/Date(1725062400000)/",
                "HasAttachments": False,
                "HasErrors": False,
                "InvoiceID": "64cd559e-8e03-46af-b461-8555285cee71",
                "InvoiceNumber": "ORC1031",
                "IsDiscounted": False,
                "LineAmountTypes": "Exclusive",
                "LineItems": [
                    {
                        "AccountCode": "200",
                        "Description": "Desktop/network support via email & phone.\r\nPer month fixed fee for minimum 20 hours/month.",
                        "ItemCode": "Support-M",
                        "LineAmount": 500.0,
                        "LineItemID": "ef456fb9-3983-473e-bda2-5ed06a5106ae",
                        "Quantity": 1.0,
                        "TaxAmount": 50.0,
                        "TaxType": "OUTPUT",
                        "Tracking": [],
                        "UnitAmount": 500.0,
                    }
                ],
                "Overpayments": [],
                "Payments": [],
                "Prepayments": [],
                "Reference": "Monthly support",
                "Status": "DRAFT",
                "SubTotal": 500.0,
                "Total": 550.0,
                "TotalTax": 50.0,
                "Type": "ACCREC",
                "UpdatedDateUTC": "/Date(1222863623773+0000)/",
                "OnlineInvoiceUrl": "https://go.xero.com/",
            },
            {
                "AmountCredited": 0.0,
                "AmountDue": 1485.0,
                "AmountPaid": 0.0,
                "Contact": {
                    "Addresses": [],
                    "ContactGroups": [],
                    "ContactID": "4ab343ad-1ebb-4afe-9d48-1814a93c2081",
                    "ContactPersons": [],
                    "HasAttachments": False,
                    "HasValidationErrors": False,
                    "Name": "ABPA",
                    "Phones": [],
                },
                "CreditNotes": [],
                "CurrencyCode": "AUD",
                "Date": "/Date(1722902400000)/",
                "DueDate": "/Date(1724198400000)/",
                "HasAttachments": False,
                "HasErrors": False,
                "InvoiceID": "bfbb7c45-de02-45e7-b065-d9863ecfb0d8",
                "InvoiceNumber": "",
                "IsDiscounted": False,
                "LineAmountTypes": "Exclusive",
                "LineItems": [
                    {
                        "AccountCode": "485",
                        "Description": "Annual subscription for Aus Business Prof Assoc ",
                        "LineAmount": 1350.0,
                        "LineItemID": "4ac009bf-a4f3-4cd8-a42d-2075d9a335d3",
                        "Quantity": 2.0,
                        "TaxAmount": 135.0,
                        "TaxType": "INPUT",
                        "Tracking": [],
                        "UnitAmount": 675.0,
                    }
                ],
                "Overpayments": [],
                "Payments": [],
                "Prepayments": [],
                "Reference": "",
                "Status": "SUBMITTED",
                "SubTotal": 1350.0,
                "Total": 1485.0,
                "TotalTax": 135.0,
                "Type": "ACCPAY",
                "UpdatedDateUTC": "/Date(1222926480013+0000)/",
                "OnlineInvoiceUrl": "https://go.xero.com/",
            },
            {
                "AmountCredited": 0.0,
                "AmountDue": 115.2,
                "AmountPaid": 0.0,
                "Contact": {
                    "Addresses": [],
                    "ContactGroups": [],
                    "ContactID": "e1826204-cc0a-42a5-a6d0-4b352d9d5953",
                    "ContactPersons": [],
                    "HasAttachments": False,
                    "HasValidationErrors": False,
                    "Name": "Carlton Technical Books",
                    "Phones": [],
                },
                "CreditNotes": [],
                "CurrencyCode": "AUD",
                "Date": "/Date(1723766400000)/",
                "DueDate": "/Date(1723766400000)/",
                "HasAttachments": False,
                "HasErrors": False,
                "InvoiceID": "88e77f0f-54a5-4efc-a979-7e22223cc4d7",
                "InvoiceNumber": "",
                "IsDiscounted": False,
                "LineAmountTypes": "Exclusive",
                "LineItems": [
                    {
                        "Description": "Brand You & Think Big for office",
                        "LineAmount": 115.2,
                        "LineItemID": "c8554e4f-679d-4787-a386-0449d02f11dd",
                        "Quantity": 1.0,
                        "TaxAmount": 0.0,
                        "Tracking": [],
                        "UnitAmount": 115.2,
                    }
                ],
                "Overpayments": [],
                "Payments": [],
                "Prepayments": [],
                "Reference": "",
                "Status": "DRAFT",
                "SubTotal": 115.2,
                "Total": 115.2,
                "TotalTax": 0.0,
                "Type": "ACCPAY",
                "UpdatedDateUTC": "/Date(1222926504467+0000)/",
                "OnlineInvoiceUrl": "https://go.xero.com/",
            },
        ]
    }
]
