# Generated by Django 5.0.7 on 2024-09-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0005_userdocument_userdocument_unique_user_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='pdf_store_id',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
    ]
