# Generated by Django 5.0.7 on 2024-09-27 07:15

import chatbot_app.models
import chatbot_app.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0006_userdocument_pdf_store_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.CharField(blank=True, choices=[('aasb', 'AASB'), ('annual_reports', 'Annual Reports')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, null=True, storage=chatbot_app.utils.CustomS3Boto3Storage(), upload_to=chatbot_app.models.Document.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
